name: navigation_app
publish_to: none

environment:
  sdk: ^3.9.2

workspace:
  - packages/navigation_api
  - packages/navigation_impl
  - packages/feature_auth
  - packages/feature_personal
  - packages/navigation_generator
  - app